# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-MIME
version:      1.82
version_from: MIME.pm
installdirs:  site
requires:
    Email::MIME::ContentType:      1.0
    Email::MIME::Encodings:        1.3
    Email::Simple:                 1.91
    Encode:                        1.9801
    MIME::Types:                   1.13
    Test::More:                    0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
